package org.sunt.sqlanalysis.lineage.model

/**
 *  @param label 关系名称
 *  @param desc 关系说明
 *
 */
enum class RelationType(val label: String, val desc: String, val sample: String) {

    EQUIVALENT("等价关系", "直接引用", "FROM A a JOIN B b ON a.x = b.y, then A.x is EQUIVALENT to B.y"),

    DIRECTCOPY("复制关系","A直接生成B", "INSERT INTO B(y) AS SELECT x FROM A, then B.y is DIRECT COPY of A.x"),
    TRANSFORM("转换关系", "经函数转换，特殊的GENERATION", "(SELECT CAST(a AS INT) AS y FROM A) AS B, then B.y is TRANSFROM FROM A.x "),
    GENERATE("计算生成", "多个字段计算后生成", "(SELECT A.x+B.y AS z FROM A,B ) AS C, then C.z is GENERATED by A.x and B.y"),
    AGGREGATE("聚合生成", "通过聚合函数生成", "(SELECT MAX(x) AS y FROM A) AS B, then B.y is AGGREGATION of A.x"),

    CONDITION("过滤条件", "在过滤条件中的依赖关系", "(SELECT A.m AS y FROM A where x = 1) AS B, then B.y is FILTERED by A.x")


}