rootProject.name = "pms"

include("module-dependency")
include("module-commons")
include("service-storage")
include("service-customize")
include("service-project")
include("service-search")
include("service-schedule")
include("module-multitenant")
include("service-auth")
include("service-workflow")
include("service-document")
include("service-subversion")
include("service-messaging")
include("service-git")
include("module-sqlanalysis")
include("service-intelliquery")
include("service-metadata")
include("module-storage")
