server:
  port: 8005

spring:
  application:
    name: identity
  datasource:
    url: jdbc:mysql://localhost:3306/pms?serverTimezone=UTC
    username: root
    password: abc123
  flyway:
    enabled: true
  cloud:
    nacos:
      server-addr: 192.168.2.112:8848