DROP TABLE IF EXISTS `upload_file`;
CREATE TABLE IF NOT EXISTS `upload_file`
(
    id          INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
    parent_id   INTEGER UNSIGNED NOT NULL DEFAULT 0 COMMENT '所属文件ID',
    file_name   VARCHAR(128)     NOT NULL COMMENT '文件名',
    file_path   VARCHAR(256)     NOT NULL COMMENT '文件路径',
    file_size   INTEGER UNSIGNED NOT NULL DEFAULT 0 COMMENT '文件大小',
    file_crc32  INTEGER          NOT NULL DEFAULT 0 COMMENT '文件hash',
    file_suffix VARCHAR(8)       NOT NULL DEFAULT '' COMMENT '文件后缀',
    create_at   DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by   INTEGER UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建人ID',
    referenced  INTEGER UNSIGNED NOT NULL DEFAULT 1 COMMENT '引用次数',
    tenant_id   INTEGER          NOT NULL DEFAULT 0 COMMENT '租户ID'
) ENGINE = INNODB
  AUTO_INCREMENT = 10000
  DEFAULT CHARSET = UTF8MB4
  ROW_FORMAT = DYNAMIC COMMENT ='文件表';

