server:
  port: 8003
pms:
  baseDir: file:\\D:\

spring:
  application:
    name: storage
  cloud:
    nacos:
      config:
        server-addr: 192.168.2.112:8848
        file-extension: yaml
      discovery:
        server-addr: 192.168.2.112:8848